### ISSUE TITLE
Type name is the same as the component name

### ISSUE THREAD

**Issue by enkot** [antfu/nuxt-module-eslint-config#2]
### Describe the bug

Eslint removes `type` keyword from the import if `ts/consistent-type-imports` is used and component with the same name used in the template.
Not sure how to properly solve such problems.

### Reproduction

https://stackblitz.com/edit/github-pcxlcz?file=app.vue

### System Info

```Shell
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules, eslintConfig
- Runtime Modules:  nuxt-module-eslint-config@0.0.1
- Build Modules:    -
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
That is because you also reference `CarItem` in your template as component and ESLint gets confused with it. I don't think it's something fixable. I's suggest you rename the type and avoid using the same name.
