### ISSUE TITLE
using this on ci forces us to run dev first

### ISSUE THREAD

**Issue by stephenjason89** [antfu/nuxt-module-eslint-config#5]
### Describe the bug

We're encountering numerous linting errors on our CI due to the ESLint configuration being located inside the .nuxt directory, which only becomes available after executing the run dev command. Is there a way to create a script that can generate this configuration file without the necessity to initiate the development server?

### Reproduction

-

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 10.07 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.14.1 - ~/Library/pnpm/pnpm
    bun: 1.0.27 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.0
```

### Used Package Manager

bun

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
You can run `nuxi prepare`

**Comment by stephenjason89** [comment]
Thank you @antfu, just tried it again and it works.
